.PHONY: clean All

All:
	@echo "----------Building project:[ number_one - Debug ]----------"
	@cd "number_one" && "$(MAKE)" -f  "number_one.mk"
clean:
	@echo "----------Cleaning project:[ number_one - Debug ]----------"
	@cd "number_one" && "$(MAKE)" -f  "number_one.mk" clean
